# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 09:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ealauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('metadata_json', django.contrib.postgres.fields.jsonb.JSONField(max_length=2048)),
                ('datatableinfo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ealauth.DataTableInfo')),
            ],
            options={
                'verbose_name': 'DataTable',
                'verbose_name_plural': 'DataTablepodes',
            },
        ),
        migrations.AlterUniqueTogether(
            name='columninfo',
            unique_together=set([('name', 'datatableinfo_id')]),
        ),
    ]
