# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 09:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ealauth', '0002_auto_20161217_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='columninfo',
            options={'verbose_name': 'ColumnInfo', 'verbose_name_plural': 'ColumnInfos'},
        ),
        migrations.AlterModelOptions(
            name='datatableinfo',
            options={'verbose_name': 'DataTable', 'verbose_name_plural': 'DataTables'},
        ),
        migrations.AlterField(
            model_name='columninfo',
            name='metadata_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(max_length=2048, null=True),
        ),
    ]
