# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 09:49
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ealauth', '0003_auto_20161217_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('owner_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='mapdefinition',
            unique_together=set([('name', 'owner_user_id')]),
        ),
    ]
