# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ealauth', '0004_auto_20161217_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeometryLinkage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_column', models.CharField(max_length=256)),
                ('attr_column', models.CharField(max_length=256)),
                ('attr_table_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ealauth.DataTableInfo')),
            ],
        ),
        migrations.CreateModel(
            name='GeometrySource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry_type', models.CharField(max_length=256)),
                ('column', models.CharField(max_length=256)),
                ('srid', models.IntegerField()),
                ('gid', models.CharField(max_length=256)),
                ('datatableinfo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ealauth.DataTableInfo')),
            ],
        ),
        migrations.CreateModel(
            name='GeometrySourceProjected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srid', models.IntegerField()),
                ('column', models.CharField(max_length=256)),
                ('geometry_source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ealauth.GeometrySource')),
            ],
        ),
        migrations.AddField(
            model_name='geometrylinkage',
            name='geo_source_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ealauth.GeometrySource'),
        ),
    ]
