# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ealauth', '0006_auto_20161217_1117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataTableInfo',
            new_name='TableInfo',
        ),
        migrations.RenameField(
            model_name='columninfo',
            old_name='datatableinfo_id',
            new_name='tableinfo_id',
        ),
        migrations.RenameField(
            model_name='geometrysource',
            old_name='datatableinfo_id',
            new_name='tableinfo_id',
        ),
        migrations.AlterUniqueTogether(
            name='columninfo',
            unique_together=set([('name', 'tableinfo_id')]),
        ),
    ]
