# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ealauth', '0007_auto_20161217_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columninfo',
            name='tableinfo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='ealauth.TableInfo'),
        ),
    ]
