# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ealauth', '0008_auto_20161217_1337'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='columninfo',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='columninfo',
            name='tableinfo_id',
        ),
        migrations.RemoveField(
            model_name='geometrylinkage',
            name='attr_table_info_id',
        ),
        migrations.RemoveField(
            model_name='geometrylinkage',
            name='geo_source_id',
        ),
        migrations.RemoveField(
            model_name='geometrysource',
            name='tableinfo_id',
        ),
        migrations.RemoveField(
            model_name='geometrysourceprojected',
            name='geometry_source_id',
        ),
        migrations.DeleteModel(
            name='ColumnInfo',
        ),
        migrations.DeleteModel(
            name='GeometryLinkage',
        ),
        migrations.DeleteModel(
            name='GeometrySource',
        ),
        migrations.DeleteModel(
            name='GeometrySourceProjected',
        ),
        migrations.DeleteModel(
            name='TableInfo',
        ),
    ]
