# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ealauth', '0009_auto_20170112_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdefinition',
            name='shared',
            field=models.IntegerField(choices=[(1, 'Private'), (2, 'Authenticated Users Only'), (3, 'Public On The Web')], default=1),
        ),
    ]
