# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ealauth', '0011_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
