# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 10:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ealauth', '0012_auto_20170719_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite_tables',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='recent_tables',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
