# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ealauth', '0013_auto_20171025_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdefinition',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
