# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ealauth', '0014_auto_20180425_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdefinition',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
