# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 04:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ealauth', '0015_auto_20180527_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favourite_tables',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recent_tables',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
